-- =============================================================================
-- 01_setup_database.sql — Create database, schema, and roles for Prefect SPCS
-- =============================================================================
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS PREFECT_DB;
CREATE SCHEMA IF NOT EXISTS PREFECT_DB.PREFECT_SCHEMA;

-- Service role for SPCS services
CREATE ROLE IF NOT EXISTS PREFECT_ROLE;
GRANT USAGE ON DATABASE PREFECT_DB TO ROLE PREFECT_ROLE;
GRANT USAGE ON SCHEMA PREFECT_DB.PREFECT_SCHEMA TO ROLE PREFECT_ROLE;

-- Least-privilege grants for SPCS operations
GRANT CREATE TABLE ON SCHEMA PREFECT_DB.PREFECT_SCHEMA TO ROLE PREFECT_ROLE;
GRANT CREATE VIEW ON SCHEMA PREFECT_DB.PREFECT_SCHEMA TO ROLE PREFECT_ROLE;
GRANT CREATE STAGE ON SCHEMA PREFECT_DB.PREFECT_SCHEMA TO ROLE PREFECT_ROLE;
GRANT CREATE FUNCTION ON SCHEMA PREFECT_DB.PREFECT_SCHEMA TO ROLE PREFECT_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA PREFECT_DB.PREFECT_SCHEMA TO ROLE PREFECT_ROLE;
GRANT CREATE SERVICE ON SCHEMA PREFECT_DB.PREFECT_SCHEMA TO ROLE PREFECT_ROLE;
GRANT CREATE IMAGE REPOSITORY ON SCHEMA PREFECT_DB.PREFECT_SCHEMA TO ROLE PREFECT_ROLE;
GRANT CREATE SECRET ON SCHEMA PREFECT_DB.PREFECT_SCHEMA TO ROLE PREFECT_ROLE;
GRANT CREATE NETWORK RULE ON SCHEMA PREFECT_DB.PREFECT_SCHEMA TO ROLE PREFECT_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA PREFECT_DB.PREFECT_SCHEMA TO ROLE PREFECT_ROLE;

-- Allow creating services and compute pools
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE PREFECT_ROLE;

GRANT ROLE PREFECT_ROLE TO ROLE ACCOUNTADMIN;

USE ROLE PREFECT_ROLE;
USE DATABASE PREFECT_DB;
USE SCHEMA PREFECT_SCHEMA;
